#ifndef LIBZELLO_VERSION_H
#define LIBZELLO_VERSION_H

#define LIBZELLO_VERSION_MAJOR 0
#define LIBZELLO_VERSION_MINOR 1
#define LIBZELLO_VERSION_PATCH 0

#ifdef LIBZELLO_GIT_HASH
#define LIBZELLO_VERSION_STRING "0.1.0+" LIBZELLO_GIT_HASH
#else
#define LIBZELLO_VERSION_STRING "0.1.0"
#endif

#endif
